# Site settings
title: Luis Valle's Portfolio
tagline: "Let's make games together"
url: "http://luisvalle.net" # The base hostname & protocol for your site. Use it if you need absolute URL's
permalink: /:title/
font: <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

# Social
socialimg: /img/social.jpg # be sure to change this image
facebook: fbusername
twitter: luisvalle94
github: luisit094
googleplus: gusername
instagram: luisito_dc5

# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
